version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: password
      TZ: 'Asia/Tehran'
      PGTZ: 'Asia/Tehran'
    ports:
      - 5000:5432


volumes:
  postgres:

